spring:
  application:
    name: agent
  data:
    mongodb:
      host: mongodb
      port: 27017
      username: rootuser
      password: rootpass
      authentication-database: admin
      database: RMM
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: true
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
kafka:
  group:
    id: spring-boot-api-consumer
  bootstrap-servers: kafka:
logging:
  level:
    org:
      springframework:
        data: debug
agent:
  ip: 185.165.117.108
server:
  port: 8080



