spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: 'false'
    bootstrap-servers: 127.0.0.1:9092
  application:
    name: agent
  data:
    mongodb:
      host: 192.168.182.149
      port: 27017
      username: rootuser
      password: rootpass
      authentication-database: admin
      database: RMM
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: true
    host: 192.168.182.149
    port: 5672
    username: guest
    password: guest
kafka:
  group:
    id: spring-boot-api-consumer
logging:
  level:
    org:
      springframework:
        data: debug
agent:
  ip: 185.165.117.108



