spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8051

gcp:
  firebase:
    service-account: classpath:rmmproject.json
